require("opt")
require("plugin")
require("map")
require("extra")
  
require("plug_cfgs.lightline")
require("plug_cfgs.bufferline")
require("plug_cfgs.nvim_catppuccin")
require("plug_cfgs.indent_blankline")
require("plug_cfgs.toggle_term")

require("plug_cfgs.nvim-tree")
require("plug_cfgs.telescope")
require("plug_cfgs.translator")

require("plug_cfgs.nvim_term")
require("plug_cfgs.nvim_cmp")
require("plug_cfgs.nvim_lsp")
require("plug_cfgs.nvim_lsp_server")
require("plug_cfgs.lsp_signature_help")
require("plug_cfgs.luasnip")
require("plug_cfgs.x-ray_go")
require("plug_cfgs.treesitter")
require("plug_cfgs.symbol_outline")
require("plug_cfgs.lspkind")

require("plug_cfgs.gitsigns")
require("plug_cfgs.diffview")
require("plug_cfgs.vim_bookmark")
