-- require("plugin")
-- require("plug_cfgs.nvlime")

require("opt")
require("map")
require("extra")
require("plugin_lazy")

require("plug_cfgs.neodev")
require("plug_cfgs.nvim_catppuccin")
-- require("plug_cfgs.tokyonight")
-- require("plug_cfgs.nvlime")
-- plugin config
require("plug_cfgs.nvim_pair")
-- require("plug_cfgs.lightline")
require("plug_cfgs.lualine")
require("plug_cfgs.nvim_autopairs")
require("plug_cfgs.bufferline")
require("plug_cfgs.indent_blankline")
require("plug_cfgs.toggle_term")

-- require("plug_cfgs.nvim_conjure")
require("plug_cfgs.nvim-tree")
require("plug_cfgs.telescope")
require("plug_cfgs.translator")

require("plug_cfgs.nvim_lsp_server")
-- require("plug_cfgs.nvim_term")
require("plug_cfgs.nvim_cmp")

require("plug_cfgs.lsp_signature_help")
require("plug_cfgs.luasnip")
require("plug_cfgs.x-ray_go")
require("plug_cfgs.treesitter")
require("plug_cfgs.treesj")
--  require("plug_cfgs.aerial")
require("plug_cfgs.symbol_outline")
require("plug_cfgs.lspkind")
-- require("plug_cfgs.rust_tools")

require("plug_cfgs.gitsigns")
require("plug_cfgs.diffview")
require("plug_cfgs.vim_bookmark")
require("plug_cfgs.venn")
require("plug_cfgs.orgmode")
require("plug_cfgs.which_keys")
require("plug_cfgs.navbuddy")
-- require("plug_cfgs.nvim_dap")
require("plug_cfgs.oil")
require("plug_cfgs.bigfile")
require("plug_cfgs.ufo")
require("plug_cfgs.glow")
require("plug_cfgs.sniprun")
require("plug_cfgs.flash")
require("plug_cfgs.notify")
require("plug_cfgs.zen")
require("plug_cfgs.noice")

-- require("plug_cfgs.startup")
require("plug_cfgs.dashboard")
